name: Deploy to github page

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run npm script
        run: |
          git config user.name "Albert Cheung"
          git config user.email "albert.cheung@harmonicinc.com"
          npm install
          npm run deploy
